"""edit student

Revision ID: 572f61f51407
Revises: bd3412b1c672
Create Date: 2021-10-12 21:39:42.948233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572f61f51407'
down_revision = 'bd3412b1c672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    # ### end Alembic commands ###
