"""add meal, excursion, other

Revision ID: 76085256ce3f
Revises: 572f61f51407
Create Date: 2021-10-23 14:24:10.390247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76085256ce3f'
down_revision = '572f61f51407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('balance_delta', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('meal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('meal_delta', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('excursion', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('excursion_delta', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('other', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('balances', sa.Column('other_delta', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'other_delta')
    op.drop_column('balances', 'other')
    op.drop_column('balances', 'excursion_delta')
    op.drop_column('balances', 'excursion')
    op.drop_column('balances', 'meal_delta')
    op.drop_column('balances', 'meal')
    op.drop_column('balances', 'balance_delta')
    # ### end Alembic commands ###
