"""log1

Revision ID: 83a9a0f936ff
Revises: f663391c9ad2
Create Date: 2022-09-12 17:39:18.999350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a9a0f936ff'
down_revision = 'f663391c9ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_username', sa.String(length=25), nullable=False))
    op.create_index(op.f('ix_logs_user_username'), 'logs', ['user_username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_user_username'), table_name='logs')
    op.drop_column('logs', 'user_username')
    # ### end Alembic commands ###
