"""log null

Revision ID: 85383f6cafe3
Revises: 83a9a0f936ff
Create Date: 2022-09-22 13:06:38.116667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85383f6cafe3'
down_revision = '83a9a0f936ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'info',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('logs', 'user_id',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               nullable=True)
    op.alter_column('logs', 'user_username',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('logs', 'user_firstname',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('logs', 'user_lastname',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'user_lastname',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('logs', 'user_firstname',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('logs', 'user_username',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('logs', 'user_id',
               existing_type=sa.NUMERIC(precision=10, scale=0),
               nullable=False)
    op.alter_column('logs', 'info',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
