"""Final 1.0

Revision ID: 8dd8083d71bc
Revises: 
Create Date: 2021-09-18 14:35:45.529282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd8083d71bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_fio', sa.String(length=50), nullable=False),
    sa.Column('last', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_balance'), 'balances', ['balance'], unique=False)
    op.create_index(op.f('ix_balances_last'), 'balances', ['last'], unique=False)
    op.create_index(op.f('ix_balances_loaded_at'), 'balances', ['loaded_at'], unique=False)
    op.create_index(op.f('ix_balances_student_fio'), 'balances', ['student_fio'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_fio', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_student_fio'), 'students', ['student_fio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_fio'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_balances_student_fio'), table_name='balances')
    op.drop_index(op.f('ix_balances_loaded_at'), table_name='balances')
    op.drop_index(op.f('ix_balances_last'), table_name='balances')
    op.drop_index(op.f('ix_balances_balance'), table_name='balances')
    op.drop_table('balances')
    # ### end Alembic commands ###
