"""add admin & rkл

Revision ID: 956813d54c30
Revises: f0238e063e84
Create Date: 2021-11-26 13:58:26.281939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956813d54c30'
down_revision = 'f0238e063e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admin', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('rk', sa.Boolean(), nullable=False))
    op.drop_index('telegram_id', table_name='students')
    op.create_index(op.f('ix_students_admin'), 'students', ['admin'], unique=False)
    op.create_index(op.f('ix_students_rk'), 'students', ['rk'], unique=False)
    op.create_index(op.f('ix_students_telegram_id'), 'students', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_telegram_id'), table_name='students')
    op.drop_index(op.f('ix_students_rk'), table_name='students')
    op.drop_index(op.f('ix_students_admin'), table_name='students')
    op.create_index('telegram_id', 'students', ['telegram_id'], unique=False)
    op.drop_column('students', 'rk')
    op.drop_column('students', 'admin')
    # ### end Alembic commands ###
