"""modify students

Revision ID: a2d3551cb32c
Revises: 8dd8083d71bc
Create Date: 2021-09-22 23:19:37.401085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2d3551cb32c'
down_revision = '8dd8083d71bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.add_column('students', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('last_balance', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_students_disabled'), 'students', ['disabled'], unique=False)
    op.create_index(op.f('ix_students_last_balance'), 'students', ['last_balance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_last_balance'), table_name='students')
    op.drop_index(op.f('ix_students_disabled'), table_name='students')
    op.drop_column('students', 'last_balance')
    op.drop_column('students', 'disabled')
    op.alter_column('balances', 'balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
