"""add delta

Revision ID: bd3412b1c672
Revises: a2d3551cb32c
Create Date: 2021-09-24 17:18:25.242920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3412b1c672'
down_revision = 'a2d3551cb32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('delta', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'delta')
    # ### end Alembic commands ###
