"""del balance delta

Revision ID: f0238e063e84
Revises: 76085256ce3f
Create Date: 2021-10-23 14:25:59.536324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0238e063e84'
down_revision = '76085256ce3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'delta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('delta', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
